mindmap
  root((Multi-Cloud<br/>Data Platform<br/>POC))
    GCP
      Pub/Sub
      Cloud Storage
      Dataproc Serverless
      BigQuery
      Dataplex
    AWS
      Kinesis
      S3 + Iceberg
      Glue / EMR
      Redshift
      Lake Formation
    Azure
      Event Hubs
      ADLS Gen2
      Databricks
      Synapse
      Purview
    Databricks
      Auto Loader
      Delta Lake
      DLT
      DBSQL
      Unity Catalog
